config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  # static url before dynamic one !!!!!!!!!!
  # ---------------------------------
  # ---------------------------------
  # ---------------------------------
  # ---------------------------------
  get 'tasks/new', to: 'tasks#new', as: :task_new
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [ :show, :edit, :update, :destroy ]

  def show
  end

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    # attention faut passer le task_parems il connaitt
    # -----------------------
    # @tasks.update(params[:task])
    @tasks.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @tasks.destroy
    redirect_to tasks_path
  end

  private
  # protection from attack !!!

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @tasks = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <%= f.label :title, "Enter the title of your task" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Enter the details of your task" %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1> Here is the page to edit your task !!!!!!</h1>
<%= render 'form', task: @tasks %>

app/views/tasks/index.html.erb
<h1>My tasks I have/need to do !</h1>


<ul>
  <% @tasks.each do |task| %>
    <li style="list-style-type: none"><%= check_box_tag task.id, task.title, task.completed %> <%= link_to task.title, task_path(task) %> <br>
      <%= link_to "Delete", task_path(task), method: "delete", data: { confirm: "Are you sure you want to delete?" } %></li>
  <% end %>
</ul>

 <%= link_to "Create a task", task_new_path %>

app/views/tasks/new.html.erb
<h1>Here you can add a new task</h1>

<%= render 'form', task: @task %>

<br>
<br>
<br>

<%= link_to "Back to tasks page", tasks_path %>

app/views/tasks/show.html.erb
<h1>More details on the <%= @tasks.title %> task !!!!</h1>
<p>Details : <%= @tasks.details %> and hurry up !!!!!!!!!!!!!!!!</p>
 <br>
 <%= link_to "Back to tasks page", tasks_path %>
 <%= link_to "Edit page to edit your tasks!!!!", edit_task_path %>